<?php

/**
 * Educacional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Educacional extends BaseEducacional
{
    public function ente_id($ente_id) {
        $datos = $this->getTable()->findOneBy("ente_id",$ente_id);
        if (!$datos){
            $this->Ente_id = $ente_id;
            return $this;
        };
        return $datos;
    }
}