<?php

/**
 * Ente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ente extends BaseEnte
{
    public function crear($dni){
        $datos = $this->getTable()->findOneBy("dni",$dni);
        if (!$datos){
            $this->dni = $dni;
            return $this;

        };
        
        return $datos;
    }
}